version: 2

builds:
  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows-gnu
      - CXX=zig c++ -target x86_64-windows-gnu
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -X main.Version={{.Version}}

archives:
  - formats:
      - zip

checksum:
  name_template: 'checksums_windows_amd64.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: jonhadfield
    name: certreader
  prerelease: auto
  name_template: "{{ .Tag }}"
